Python update-path.py "../src/main/deploy/pathplanner/paths/Algae Links.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/Coral Links.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C0-PR.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C1-PL.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C2-PL.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C3-PL.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C4-PL.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C5-PL.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C8-PR.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C9-PR.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C10-PR.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/C11-PR.path"

Python update-path.py "../src/main/deploy/pathplanner/paths/PR-C0.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/PL-C1.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/PL-C2.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/PL-C3.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/PR-C10.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/PR-C11.path"

Python update-path.py "../src/main/deploy/pathplanner/paths/SC-C6.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/SC-C7.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/SL-C3.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/SL-C4.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/SL-C5.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/SR-C8.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/SR-C9.path"
Python update-path.py "../src/main/deploy/pathplanner/paths/SR-C10.path"